---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.1-bullseye

inputs:
  - name: dp-renderer

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-renderer/ci/scripts/build.sh
